data_root_dir: /data/processed_datasets/processed_datasets/ehr_foundation_data/ohdsi_cumc_deid/
data_dir: ./data/files/
downstream_task: readmission
data_seed: 123

task: classification
batch_size: 16
num_points: 2000
d_model: 256
emb_depth: 4
pred_depth: 1
nhead: 8
dim_feedforward: 512
num_layers: 8
dropout: 0
bound_std: True
lr: 0.0001
num_steps: 200000
num_warmup_steps: 5000
checkpoint_interval: 1000
train_seed: 42

temp: 0.1
lr_afa: 0.00005
num_steps_afa: 50000
train_selector_only: False
afa_training_strategy: sequential
inner_loop_steps: 5
checkpoint_interval_afa: 1000

eval_kernel: rbf
eval_seed: 42
eval_num_batches: 100
eval_batch_size: 1
eval_data_dir: ./data/eval
log_dir: ./logs/cuimc_{num_points}_{downstream_task}/

test_num_batches: 20
test_num_batches_afa: 50
test_num_batches_bench_afa: 10
test_seed: 123

num_gpus: 3
nn_hidden_dim: 128
lr_baseline: 0.001
nepochs_baseline: 100
batch_size_baseline: 64
val_frac_baseline: 0.2
lr_gdfs: 0.0005
nepochs_gdfs: 50
train_predictor_gdfs: False
temp_gdfs: 0.1
