experiment: miniboone
data_dir: ./data/files/
downstream_task: "y" # mortality, stroke, los, readmission, nafld
data_seed: 123
feature_selection: False
margin: False
pool_size: 5000
test_pool_size: 10000
verbose: True
label_dim: 1

task: classification
batch_size: 8
num_points: 1000
d_model: 256
emb_depth: 4
pred_depth: 1
nhead: 4
dim_feedforward: 512
num_layers: 6
dropout: 0
bound_std: True
lr: 0.0001
num_steps: 50000
num_warmup_steps: 500
checkpoint_interval: 500
train_seed: 42
embed: set

temp: 0.1
temp_decay: False
lr_selector: 0.0001
lr_backbone: 0.00001
batch_size_afa: 8
num_steps_afa: 50000
num_steps_afa_warmup: 500
scheduler_afa: None
from_checkpoint: True
freeze_encoder: False
afa_training_strategy: sequential
inner_loop_steps: 1
entropy_weight: 0
checkpoint_interval_afa: 200

eval_kernel: rbf
eval_seed: 42
eval_batch_size: 200
eval_data_dir: ./data/eval
log_dir: ./logs/miniboone_{num_points}/

test_points: 500
test_num_batches: 50
test_num_batches_afa: 20
test_num_batches_bench_afa: 50
test_seed: 123
test_context_lengths: [50, 100, 200, 500, 900]
test_missingness_rates: [0.0, 0.5, 0.75, 1.0]
test_subgroups: [1, 2, 3]
test_min_informative: 5

num_gpus: 1
nn_hidden_dim: 128
nn_dropout: 0.2
lr_baseline: 0.001
nepochs_baseline: 300
batch_size_baseline: 64
val_frac_baseline: 0.2
lr_gdfs: 0.0005
nepochs_gdfs: 50
train_predictor_gdfs: False
temp_gdfs: 0.5
log_progress: False

# RL experiment parameters
episodes: 100
buffer_size: 10000
batch_size_rl: 128
inner_loop_steps_rl: 1
lr_rl: 0.0001
target_update: 4